// <auto-generated />
using LinqQueries.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using System;

namespace LinqQueries.Migrations
{
    [DbContext(typeof(LinqQueryDbContext))]
    [Migration("20180322015542_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.0-rtm-26452");

            modelBuilder.Entity("LinqQueries.Models.Client", b =>
                {
                    b.Property<int>("ClientID")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("ClientName");

                    b.Property<string>("Region");

                    b.HasKey("ClientID");

                    b.ToTable("Clients");
                });

            modelBuilder.Entity("LinqQueries.Models.Project", b =>
                {
                    b.Property<int>("ProjectID")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("ClientID");

                    b.Property<DateTime>("DeliveryDate");

                    b.Property<DateTime>("KickoffDate");

                    b.Property<string>("ProjectName");

                    b.Property<decimal>("Revenue");

                    b.Property<string>("Status");

                    b.HasKey("ProjectID");

                    b.ToTable("Projects");
                });

            modelBuilder.Entity("LinqQueries.Models.ProjectResource", b =>
                {
                    b.Property<int>("ProjectResourceID")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("AllocatedHours");

                    b.Property<int>("ProjectID");

                    b.Property<int>("ResourceID");

                    b.HasKey("ProjectResourceID");

                    b.ToTable("ProjectResources");
                });

            modelBuilder.Entity("LinqQueries.Models.Resource", b =>
                {
                    b.Property<int>("ResourceID")
                        .ValueGeneratedOnAdd();

                    b.Property<decimal>("HourlyRate");

                    b.Property<string>("ResourceName");

                    b.Property<string>("Role");

                    b.Property<int>("ServiceYears");

                    b.HasKey("ResourceID");

                    b.ToTable("Resources");
                });
#pragma warning restore 612, 618
        }
    }
}
