// <auto-generated />
using Group1_Assn4.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using System;

namespace Group1_Assn4.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20180323021129_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.2-rtm-10011");

            modelBuilder.Entity("Group1_Assn4.Models.Client", b =>
                {
                    b.Property<int>("ClientID")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("ClientName");

                    b.Property<string>("Region");

                    b.HasKey("ClientID");

                    b.ToTable("Clients");
                });

            modelBuilder.Entity("Group1_Assn4.Models.Project", b =>
                {
                    b.Property<int>("ProjectID")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("ClientID");

                    b.Property<DateTime>("DeliveryDate");

                    b.Property<DateTime>("KickOffDate");

                    b.Property<string>("ProjectName");

                    b.Property<decimal>("Revenue");

                    b.Property<string>("Status");

                    b.HasKey("ProjectID");

                    b.HasIndex("ClientID");

                    b.ToTable("Projects");
                });

            modelBuilder.Entity("Group1_Assn4.Models.ProjectResource", b =>
                {
                    b.Property<int>("ProjectResourceID")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("AllocatedHours");

                    b.Property<int>("ProjectID");

                    b.Property<int>("ResourceID");

                    b.HasKey("ProjectResourceID");

                    b.HasIndex("ProjectID");

                    b.HasIndex("ResourceID");

                    b.ToTable("ProjectResources");
                });

            modelBuilder.Entity("Group1_Assn4.Models.Resource", b =>
                {
                    b.Property<int>("ResourceID")
                        .ValueGeneratedOnAdd();

                    b.Property<decimal>("HourlyRate");

                    b.Property<string>("ResourceName");

                    b.Property<string>("Role");

                    b.Property<int>("ServiceYears");

                    b.HasKey("ResourceID");

                    b.ToTable("Resources");
                });

            modelBuilder.Entity("Group1_Assn4.Models.Project", b =>
                {
                    b.HasOne("Group1_Assn4.Models.Client", "Client")
                        .WithMany("Projects")
                        .HasForeignKey("ClientID")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Group1_Assn4.Models.ProjectResource", b =>
                {
                    b.HasOne("Group1_Assn4.Models.Project", "Project")
                        .WithMany()
                        .HasForeignKey("ProjectID")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Group1_Assn4.Models.Resource", "Resource")
                        .WithMany()
                        .HasForeignKey("ResourceID")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
